const { writeFile, existsSync, mkdirSync } = require('fs')
const { argv } = require('yargs')

require('dotenv').config()

const environment = argv.environment
const writeFileUsingFS = (targetPath: any, environmentFileContent: any) => {
  writeFile(targetPath, environmentFileContent, (err: any) => {
    if (err) {
      console.log(err)
    }
    if (environmentFileContent !== '') {
      console.log(`Wrote variables to ${targetPath}`)
    }
  })
}

const envDirectory = './src/environments'

if (!existsSync(envDirectory)) {
  mkdirSync(envDirectory)
}

writeFileUsingFS('./src/environments/environment.ts', '')
writeFileUsingFS('./src/environments/environment.prod.ts', '')

const isProduction = environment === 'prod'

const targetPath = isProduction
  ? './src/environments/environment.prod.ts'
  : './src/environments/environment.ts'

const environmentFileContent = `
  // This file was autogenerated by dynamically running setEnv.ts and using dotenv for managing API key secrecy
  export const environment = {
    production: ${isProduction},
    FIREBASE_API_KEY: '${process.env['API_KEY']}'
  };
`

writeFileUsingFS(targetPath, environmentFileContent)
