name: Angular CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16]

    env:
      CI: true
      THE_MOVIE_DB_API_KEY: ${{ secrets.THE_MOVIE_DB_API_KEY }}

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run lint --fix && npx prettier --write src/**/*.ts src/**/*.html src/**/*.scss 
    run: |
      echo "The GitHub Action Secret will be masked:  "
      echo ${{ secrets.THE_MOVIE_DB_API_KEY }}
    - run: npm run build